config/routes.rb
Rails.application.routes.draw do
  resources :surveys do
    member do
      post 'submission'
      post 'invite'
      post 'results'
      post 'questions'
    end
  end
  devise_for :users
  root to: 'surveys#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :survey
  belongs_to :user
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :survey
  belongs_to :user
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  has_many :submissions
  has_many :permissions
  has_many :users, through: :permissions

  scope :permitted, lambda { |user_id|
    permitted_ids = Permission.where(user_id: user_id).pluck(:survey_id)
    where(closed: false).or(where(user_id: user_id)).or(where(id: permitted_ids))
  }

  def self.seed(count, titles, questions, options, closed: false)
    user_ids = User.ids
    count.times do |i|
      Survey.create(
        user_id: user_ids.sample,
        title: titles[i],
        questions: questions[i],
        options: options[i],
        closed: closed
      )
    end
  end

  def permit(email)
    user = User.find_by(email: email)
    Permission.create(user_id: user.id, survey_id: id) if user
  end

  def permitted?(user_id)
    !closed || users.find_by(id: user_id) || (self.user_id == user_id)
  end

  def submitted?(user_id)
    submissions.find_by(user_id: user_id)
  end

  def submit(user_id, data)
    Submission.create(survey_id: id, user_id: user_id, choices: data)
  end

  def options_lengths
    options.map { |option| option.length() }
  end

  def creator?(user_id)
    self.user_id == user_id
  end

  def aggregrates
    value_counts = []

    rows = submissions.pluck(:choices).transpose.map! do |row|
      row.map! { |x| x.to_i }
    end

    rows.each_with_index do |row, index|
      value_counts << [*0..options_lengths[index] - 1].map do |x|
        [x, row.count(x)]
      end.to_h
    end

    value_counts
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.seed(count)
    count.times do
      User.create(
        email: Faker::Internet.email,
        password: Faker::Internet.password
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :submission, :invite, :questions, :results]
  before_action :authorize, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.permitted(current_user.id).includes(:users, :submissions)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was succesfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def submission
    if submitted_options.length == @survey.questions.length
      @survey.submit(current_user.id, submitted_options)
      flash[:notice] = 'Survey submitted successfully!'
    else
      flash[:notice] = 'Some options have not been filled!'
    end
  end

  def invite
    email = params[:email]
    user = User.find_by(email: email)
    if user
      if @survey.permitted?(user.id)
        flash[:notice] = 'User already has permissions to the survey!'
      else
        @survey.permit(user.id)
        flash[:notice] = 'User invited'
      end
    else
      flash[:notice] = 'User not found'
    end
  end

  def questions
    flash[:notice] = "Survey loaded"
  end

  def results
    flash[:notice] = "Results loaded"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find_by(id: params[:id])
      unless @survey
        flash[:notice] = 'The resource does not exist!'
        redirect_to surveys_path
      end
    end

    def authorize
      unless @survey.permitted?(current_user.id)
        flash[:notice] = 'The resource does not exist!'
        redirect_to surveys_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      permitted_params = params.permit(:closed, :title, questions: [], options: {})

      {
        title: params[:title],
        closed: params[:closed] == 'on',
        user_id: current_user.id,
        questions: permitted_params[:questions],
        options: permitted_params[:options].values
      }
    end

    def submitted_options
      permitted_questions = [*0..@survey.questions.length].map! { |x| x.to_s }
      params.permit(permitted_questions).values
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def submitted?(survey)
    survey.submitted?(current_user.id)
  end
end

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper container">
  <%= link_to 'Survey', root_path, class: 'brand-logo' %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <% unless (current_page? surveys_path) || (current_page? root_path) %>
          <li><%= link_to 'Home', surveys_path %></li>
        <% end %>

        <% unless current_page? new_survey_path %>
          <li><%= link_to 'Create a survey', new_survey_path %></li>
        <% end %>

        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <% unless current_page? new_user_session_path %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>

        <% unless current_page? new_user_registration_path %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<script>
  $(document).ready(function(){
    M.toast({html: "<%= notice || alert %>"})
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="content" class="container">
      <%= yield %>
    </div>

    <div id="notifications">
      <% if notice || alert %>
        <%= render "layouts/notifications" %>
      <% end %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Index Page</h1>

app/views/surveys/_aggregrate.html.erb
<% aggregrates = survey.aggregrates %>
<% total_submissions = survey.submissions.length %>

<% survey.questions.each_with_index do |question, q_i| %>
  <div class="card">
    <span class="card-title"><%= question %></span>
    <table class="striped centered">
      <thead>
        <tr>
          <th>Option</th>
          <th>Submissions</th>
        </tr>
      </thead>

      <tbody>
        <% survey.options[q_i].each_with_index do |option, o_i| %>
          <tr>
            <% value = aggregrates[q_i][o_i] %>
            <td><%= option %></td>
            <td><%= value %>
              <div class="progress">
                <div class="determinate" style="width: <%= 100*value/total_submissions %>%">
                </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/surveys/_form.html.erb
<form action='<%= surveys_path %>' accept-charset="UTF-8" data-remote="true" method="post">
  <div class="input-field">
    <label for="title">Title</label>
    <input id="title" type="text" name="title"/>
  </div>

  <div class="switch">
    <label>
      Public
      <input name="closed" type="checkbox">
      <span class="lever"></span>
      Private
    </label>
  </div>

  <div id='question_group'>
    <% 5.times do |i| %>
      <div id="question_group_<%= i %>">
        <br/>
        <div class="question input-field">
          <label for="question_<%= i %>">Question <%= i + 1 %></label>
          <input id="question_<%= i %>" type="text" name="questions[]"/>
        </div>

        <p>Options</p>
        <div id="options_group_<%= i %>">
          <% 3.times do |j| %>
            <div class="option input-field">
              <input type="text" placeholder="Option <%= j + 1 %>" name="options[<%= i %>][]"/>
            </div>
          <% end %>
        </div>

        <div>
          <a class="waves-effect waves-light btn" onclick="add_option(<%= i %>)">Add Option</a>
        </div>
      </div>
    <% end %>
  </div>

  <div>
    <br/>
    <a class="waves-effect waves-light btn" onclick="add_question()">Add Question</a>
  </div>

  <center>
    <input class="btn waves-effect waves-light" type="submit" name="action" value="Submit">
  </center>
</form>

<script>
  n_questions = 5;

function add_option(i){
  element = $("#options_group_" + i);
  element.append("<div class='option input-field'><input type='text' placeholder='Option " + (element.children().length + 1) + "' name='options[" + i + "][]'></div>");
}

function add_question(){
  html = "<div id='question_group_" + n_questions + "'><br/><div class='question input-field'><label for='question_" + n_questions + "'>Question " + (n_questions + 1) + "</label><input id='question_" + n_questions + "' type='text' name='questions[]'></div><p>Options</p><div id='options_group_" + n_questions + "'></div>"
  add_option_btn = "<div><a class='waves-effect waves-light btn' onclick='add_option(" + n_questions + ")'>Add Option</a></div>"
  element = $("#question_group");
  element.append(html);
  add_option(n_questions);
  add_option(n_questions);
  add_option(n_questions);
  $("#question_group_" + n_questions).append(add_option_btn);
  n_questions++;
  }
</script>

app/views/surveys/_invite.html.erb
<h4>Invite</h4>

<form action='<%= invite_survey_path(survey) %>' accept-charset="UTF-8" data-remote="true" method="post">
  <div class="input-field">
    <label for="invite">Invite People (by e-mail)</label>
    <input id="invite" type="text" name="email">
  </div>
  <input class="btn waves-effect waves-light" type="submit" name="action" value="Invite">
</form>

app/views/surveys/_questions.html.erb
<%# Materialize-CSS Styles hideously with rails form. I realize how bad this hack is. %>
<br/>
<form action='<%= submission_survey_path(survey) %>' accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <% survey.questions.each_with_index do |question, index| %>
    <div class="card">
      <span class="card-title"><%= question %></span>
      <% survey.options[index].each_with_index do |option, i| %>
        <p>
          <label>
            <% if params[index.to_s] == i.to_s %>
              <input name="<%= index %>" value="<%= i %>" type="radio" checked/>
            <% else %>
              <input name="<%= index %>" value="<%= i %>" type="radio" />
            <% end %>
            <span><%= option %>
          </label>
        </p>
      <% end %>
    </div>
  <% end %>

  <center>
    <input class="btn waves-effect waves-light" type="submit" name="action" value="Submit">
  </center>
</form>

app/views/surveys/_results.html.erb
<% aggregrates = survey.aggregrates %>
<% total_submissions = survey.submissions.length %>

<% survey.questions.each_with_index do |question, q_i| %>
  <div class="card">
    <span class="card-title"><%= question %></span>
    <table class="striped centered">
      <thead>
        <tr>
          <th>Option</th>
          <th>Submissions</th>
        </tr>
      </thead>

      <tbody>
        <% survey.options[q_i].each_with_index do |option, o_i| %>
          <tr>
            <% value = aggregrates[q_i][o_i] %>
            <td><%= option %></td>
            <td><%= value %>
              <div class="progress">
                <div class="determinate" style="width: <%= 100*value/total_submissions %>%">
                </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/surveys/_show.html.erb
<h1><%= survey.title %></h1>

<p><b>By <%= survey.user.email %>.</b></p>

<% if survey.closed && survey.creator?(current_user.id) %>
  <%= render partial: 'invite', locals: {survey: survey} %>
<% end %>

<% if submitted?(survey) %>
  <h4>Results</h4>
  <p>You have completed the survey.</p>

  <%= link_to 'See results', results_survey_path(survey), remote: true, class: 'btn waves-effect waves-light', method: :post %>
  <div id="results"></div>
<% else %>
  <h4>Submit Survey</h4>
  <p>Please complete the survey to see aggregrate results.</p>

  <%= link_to 'Start the survey' , questions_survey_path(survey), remote: true, class: 'btn waves-effect waves-light', method: :post %>
  <div id="questionnaire"></div>
<% end %>

app/views/surveys/edit.html.erb
<%= render 'form', survey: @survey %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created By</th>
      <th>Submitted?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.title, survey %></td>
        <td><%= survey.user.email %></td>
        <td>
          <% if submitted?(survey) %>
            Yes
          <% else %>
            No
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/surveys/invite.js.erb
$("#notifications").html("<%= j render 'layouts/notifications' %>");

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

app/views/surveys/questions.js.erb
$("#questionnaire").html("<%= j render partial: 'questions', locals: {survey: @survey} %>");
$("#notifications").html("<%= j render 'layouts/notifications' %>");

app/views/surveys/results.js.erb
$("#results").html("<%= j render partial: 'results', locals: {survey: @survey} %>");
$("#notifications").html("<%= j render 'layouts/notifications' %>");

app/views/surveys/show.html.erb
<%= render partial: 'show', locals: {survey: @survey} %>

app/views/surveys/submission.js.erb
$("#content").html("<%= j render partial: 'show', locals: {survey: @survey} %>");
$("#notifications").html("<%= j render 'layouts/notifications' %>");